export { Home } from './Home'
export { Skills } from './Skills'
export { Projects } from './Projects'
export { About } from './About'
export { Contact } from './Contact'
export { NotFound } from './NotFound'
